#!/usr/bin/env php
<?php
require __DIR__ . '/bootstrap/cli.php';

use App\Console\Kernel;

try {
    $kernel = new Kernel();
    $kernel->handle($argv);
} catch (\RuntimeException $e) {
    exit(1);
}
